// Neon Rift 1.6 scene integration. Rendering never advances gameplay or calls its RNG.
const nr15State={engine:null,zone:-1,mode:'booting',reason:'',previousTime:0,explosions:[],debris:[],lastDash:0,bossIntro:0,lastWave:0,sceneReady:false,quality:'auto',frames:0,frameMs:0,renderMs:0,shipPreview:{x:0,y:0,w:0,h:0}};
try{let savedQuality=localStorage.getItem('neon-rift-graphics-v1');if(['auto','low','high','ultra','compatibility'].includes(savedQuality))nr15State.quality=savedQuality;}catch(_){}
const nr15Canvas=document.createElement('canvas');nr15Canvas.id='nrScene';nr15Canvas.setAttribute('aria-hidden','true');nr15Canvas.style.pointerEvents='none';canvas.before(nr15Canvas);
const nr15OriginalRender=render;
function nr15Zone(){return NR16World.index(G?.wave||1);}
const nr15Regions=NR16World.destinations;
function nr15ApplyQuality(){const e=nr15State.engine;if(e)e.quality=nr15State.quality;
 const select=$('graphicsSelect');if(select)select.value=nr15State.quality;
 if($('graphicsBtn'))$('graphicsBtn').textContent={auto:'3D / AUTO',low:'PERFORMANCE',high:'HIGH',ultra:'ULTRA / 4K',compatibility:'2D FALLBACK'}[nr15State.quality]||'3D / AUTO';
 nr15State.staticKey='';nr16GraphicsStatus();}
function nr15Fallback(reason){nr15State.mode='compatibility';nr15State.reason=String(reason||'Compatibility selected');nr15Canvas.hidden=true;nr15State.staticKey='';document.body.classList.remove('nr3d');$('nrBuild')?.replaceChildren(document.createTextNode('1.6.0 / 2D COMPATIBILITY'));nr16GraphicsStatus();if($('nrRenderNote'))$('nrRenderNote').textContent='Compatibility renderer active. The 3D view needs WebGL 2.';}
function nr15Init(){if(nr15State.quality==='compatibility'){nr15Fallback('Player selected compatibility');return;}try{nr15State.engine=new NR15.Engine(nr15Canvas);NR15Art.build(nr15State.engine);NR16World.init(nr15State.engine);nr15State.engine.quality=nr15State.quality;nr15State.mode='webgl2';nr15Canvas.hidden=false;document.body.classList.add('nr3d');nr15State.sceneReady=true;if(!nr15Canvas.dataset.contextHandlers){nr15Canvas.dataset.contextHandlers='1';nr15Canvas.addEventListener('webglcontextlost',event=>{event.preventDefault();if(state==='playing')pauseGame();nr15Fallback('Graphics context lost. Your run is paused.');});nr15Canvas.addEventListener('webglcontextrestored',()=>{nr15State.engine=null;nr15State.zone=-1;nr15Init();nr15ApplyQuality();});}}catch(e){nr15Fallback(e.message);}}
function nr15BuildUI(){document.body.classList.add('nr15');let home=$('homeScreen').querySelector('.home-layout');let copy=home.firstElementChild,hangar=home.querySelector('.hangar');
 if(!home.querySelector('.nr-intro')){let intro=document.createElement('div');intro.className='nr-intro';for(let sel of['.eyebrow','h1','.home-copy']){let el=copy.querySelector(sel);if(el)intro.appendChild(el);}intro.querySelector('.tag').textContent='ORBITAL COMBAT / VISUAL EDITION';intro.querySelector('h1').innerHTML='NEON<span>RIFT</span>';intro.querySelector('.home-copy').textContent='Three ships. Nine hostile sectors. Build your firepower and break through.';
  let preview=document.createElement('section');preview.className='nr-preview-wrap';preview.setAttribute('aria-label','Selected ship preview');preview.innerHTML='<div class="nr-preview-label"><span>LIVE SHIP PREVIEW</span><span id="nrPreviewCode">NR / 01</span></div><div id="nrShipPreview"></div><div class="nr-preview-caption"><strong id="nrShipName">STRIKER</strong><span id="nrShipDesc">COIL-CANNON INTERCEPTOR</span></div>';
  let modes=document.createElement('div');modes.className='nr-modes';while(copy.firstChild)modes.appendChild(copy.firstChild);copy.remove();home.prepend(intro,preview);home.appendChild(modes);hangar.classList.add('nr-hangar');hangar.querySelector('.tag').textContent='SELECT AIRFRAME';hangar.querySelector('.hangar-head .muted').textContent='ALL SHIPS UNLOCKED';
  const texts={striker:['STRIKER','Balanced interceptor','105 HULL / RAPID FIRE'],ghost:['GHOST','Twin-cannon stealth craft','80 HULL / HIGH SPEED'],bastion:['BASTION','Heavy armored gunship','150 HULL / PIERCING']};for(let b of hangar.querySelectorAll('.rig')){let t=texts[b.dataset.rig];b.querySelector('strong').textContent=t[0];b.querySelector('small').innerHTML=t[1]+'<br>'+t[2];b.querySelector('svg').innerHTML=nr15RigIcon(b.dataset.rig);b.addEventListener('click',nr15Sync);}
  let build=document.createElement('span');build.id='nrBuild';build.textContent=nr15State.mode==='webgl2'?'1.6.0 / 3D VISUAL EDITION':'1.6.0 / 2D COMPATIBILITY';document.querySelector('.brand').appendChild(build);
  let note=document.createElement('p');note.id='nrRenderNote';note.textContent='';preview.appendChild(note);
  let setting=document.createElement('div');setting.className='setting';setting.innerHTML='<span>Graphics</span><button id="graphicsBtn" aria-label="Change graphics quality">3D / AUTO</button>';$('motionBtn').closest('.setting').before(setting);$('graphicsBtn').onclick=()=>{let order=['auto','low','high','ultra','compatibility'];nr15State.quality=order[(order.indexOf(nr15State.quality)+1)%3];try{localStorage.setItem('neon-rift-graphics-v1',nr15State.quality);}catch(_){}if(nr15State.quality==='compatibility')nr15Fallback('Player selected compatibility');else if(!nr15State.engine||nr15State.engine.gl.isContextLost()){nr15Init();}else{nr15State.mode='webgl2';nr15Canvas.hidden=false;document.body.classList.add('nr3d');$('nrBuild').textContent='1.6.0 / 3D VISUAL EDITION';$('nrRenderNote').textContent='';}nr15ApplyQuality();};
  let banner=document.createElement('div');banner.id='nrBossIntro';banner.setAttribute('aria-hidden','true');banner.innerHTML='<span>CAPITAL-CLASS CONTACT</span><strong id="nrBossTitle">THE GATEKEEPER</strong><small id="nrBossClass">ARMORED SIEGE CARRIER</small>';document.body.appendChild(banner);
  const ro=window.ResizeObserver?new ResizeObserver(nr15Measure):null;if(ro){ro.observe(preview);ro.observe(home);}home.parentElement.addEventListener('scroll',nr15Measure,{passive:true});window.addEventListener('resize',nr15Measure,{passive:true});
 }
 nr15ApplyQuality();nr15Measure();nr15Sync();}
function nr15RigIcon(id){let c=id==='ghost'?'#b7a3e4':id==='bastion'?'#e0b363':'#b5dce0';let path=id==='ghost'?'M30 3 39 24 57 47 45 50 32 37 30 44 28 37 15 50 3 47 21 24Z':id==='bastion'?'M21 9H39L50 24V49L37 55H23L10 49V24Z':'M30 3 37 22 47 27 55 49 42 45 30 54 18 45 5 49 13 27 23 22Z';return '<path d="'+path+'" fill="'+c+'" stroke="#081722" stroke-width="2"/><path d="M30 13 35 30 33 38H27L25 30Z" fill="#1c3444"/><path d="M19 43V51M41 43V51" stroke="'+(id==='bastion'?'#ffc76b':'#58eddf')+'" stroke-width="4"/>';}
function nr15Measure(){let p=$('nrShipPreview');if(p){let r=p.getBoundingClientRect();nr15State.shipPreview={x:r.x,y:r.y,w:r.width,h:r.height};}}
function nr15Sync(){let z=nr15Zone(),r=nr15Regions[z];document.documentElement.style.setProperty('--nr-zone',r.accent);if($('nrShipName')){$('nrShipName').textContent=RIGS[selectedRig].name;$('nrShipDesc').textContent={striker:'COIL-CANNON INTERCEPTOR',ghost:'TWIN-ENGINE STEALTH CRAFT',bastion:'HEAVY PIERCING GUNSHIP'}[selectedRig];$('nrPreviewCode').textContent='NR / '+({striker:'01',ghost:'02',bastion:'03'}[selectedRig]);}document.body.classList.toggle('nr-overdrive',!!player&&player.overdrive>0);document.body.classList.toggle('nr-critical',!!player&&player.hp/player.maxHp<.25);}
function nr15Prepare(time){const E=nr15State.engine,z=nr15Zone();if(nr15State.zone!==z){E.destroyMesh('environment');E.mesh('environment',NR16World.build(z));nr15State.zone=z;}
 E.begin();const menu=!player||state==='home';
 if(menu){let b=nr15State.shipPreview;if(!b.w)nr15Measure();const sx=b.x+b.w*.5,sy=b.y+b.h*.55;const showScale=Math.min(b.w/255,b.h/168);const menuZoom=1;let wx=1200+(sx-W/2),wy=900+(sy-H/2);E.add('hangar',wx,wy+28,0,0,showScale*.60,0,0,1,showScale*.38,showScale*.5);E.add(selectedRig,wx,wy,34,save.motion?-.55:-.55+Math.sin(time*.22)*.15,showScale*2.1,0,0,1,showScale*2.1,showScale*2.1,-.15);return{cx:1200,cy:900,zoom:menuZoom};}
 E.add('environment',0,0,0,0,1);NR16World.dynamics(E,z,time,save.motion);
 const viewLeft=camera.x-W/(2*zoom)-180,viewRight=camera.x+W/(2*zoom)+180,viewTop=camera.y-H/(2*zoom)-180,viewBottom=camera.y+H/(2*zoom)+180;
 function visible(e){return e.x>viewLeft&&e.x<viewRight&&e.y>viewTop&&e.y<viewBottom;}
 for(const e of enemies){if(e.dead||!visible(e))continue;let warm=e.warmup>0?Math.max(.05,1-e.warmup/.75):1;let angle=e.type==='boss'?e.rotation*.15:((e.chargeTime>0||e.windup>0)?e.chargeAngle:e.aimLocked?e.aimAngle:Math.atan2(player.y-e.y,player.x-e.x))+Math.PI/2;let model=e.type==='boss'?'boss'+Math.min(3,Math.max(1,e.stage)):e.type;let scale=e.type==='boss'?e.r/68:e.type==='brute'?e.r/25:e.type==='fragment'?.38:e.type==='gunner'?1:e.r/13;E.shadow(model,e.x+10,e.y+17,angle,scale*warm,.25);E.add(model,e.x,e.y,2,angle,scale*warm,e.hit>0?e.hit/.08:0,e.stun>0?.5:0,warm);}
 if(state!=='dead'){E.shadow(player.rig,player.x+10,player.y+17,player.angle+Math.PI/2,1,.3);E.add(player.rig,player.x,player.y,2,player.angle+Math.PI/2,1,0,player.overdrive>0?1:0);if(player.shieldReady)E.add('shield',player.x,player.y,8,time*.13,31,0,0,.4,31,3);for(let i=0;i<rank('orbit');i++){let a=time*2.9+i*Math.PI*2/rank('orbit');E.add('seeker',player.x+Math.cos(a)*72,player.y+Math.sin(a)*72,2,a+Math.PI/2,.32,0,1);}}
 for(const b of shots){if(!visible(b))continue;let a=Math.atan2(b.vy,b.vx)+Math.PI/2;E.add(b.critical?'boltGold':'boltCyan',b.x,b.y,3,a,b.r*.58,0,0,1,b.critical?13:9,1.7);}
 for(const b of hostileShots){if(!visible(b))continue;E.add('boltRed',b.x,b.y,3,0,b.r,0,0,1,b.r,b.r*.6);}
 for(const p of pickups){if(!visible(p))continue;E.add(p.type==='heal'?'repair':'pickup',p.x,p.y,4,save.motion?0:time*.9,p.type==='heal'?1.2:.9,0,0,Math.min(1,p.life?1:1));}
 for(const d of nr15State.debris){let t=(time-d.born);if(t<0||t>d.life)continue;E.add(d.model,d.x+d.vx*t,d.y+d.vy*t,3+18*Math.sin(t/d.life*Math.PI),d.a+t*d.spin,d.s*(1-t/d.life*.8),0,0,1-t/d.life);}
 const shakeX=save.motion?0:Math.sin(ambientTime*110)*shake,shakeY=save.motion?0:Math.cos(ambientTime*123)*shake*.65;
 return{cx:camera.x-shakeX/zoom,cy:camera.y-shakeY/zoom,zoom};}
function nr15Overlay(time,view){ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,W,H);if(!player)return;ctx.save();ctx.translate(W/2,H/2);ctx.scale(view.zoom,view.zoom);ctx.translate(-view.cx,-view.cy);ctx.lineCap='round';
 // Thrusters and trails are translucent effects, not the old outline ship drawings.
 const color=player.overdrive>0?'#ffd095':RIGS[player.rig].color;
 for(const t of trails){ctx.globalAlpha=Math.max(0,t.life/.25)*.20;ctx.strokeStyle=t.color;ctx.lineWidth=player.dashTime>0?11:4;ctx.beginPath();ctx.moveTo(t.x,t.y);ctx.lineTo(t.x-Math.cos(t.a)*18,t.y-Math.sin(t.a)*18);ctx.stroke();}
 if(state!=='dead'){ctx.save();ctx.translate(player.x,player.y);ctx.rotate(player.angle+Math.PI/2);ctx.globalCompositeOperation='lighter';let jets=player.rig==='ghost'?[-15,15]:player.rig==='bastion'?[-13,13]:[-10,10];for(const x of jets){let length=player.dashTime>0?80:22+Math.min(17,Math.hypot(player.vx,player.vy)*.05)+Math.sin(time*35)*3;let glow=ctx.createLinearGradient(x,22,x,22+length);glow.addColorStop(0,'#efffff');glow.addColorStop(.2,color);glow.addColorStop(1,color+'00');ctx.globalAlpha=.7;ctx.fillStyle=glow;ctx.beginPath();ctx.moveTo(x-2.7,23);ctx.quadraticCurveTo(x-3,30,x,23+length);ctx.quadraticCurveTo(x+3,30,x+2.7,23);ctx.fill();}ctx.restore();}
 // Original telegraphs retain their exact positions and timings.
 ctx.globalCompositeOperation='source-over';ctx.globalAlpha=1;drawSpawns(time);
 for(const e of enemies){if(e.dead||e.warmup>0)continue;if(e.windup>0&&Number.isFinite(e.chargeAngle)){ctx.save();ctx.strokeStyle=e.color;ctx.globalAlpha=.6;ctx.lineWidth=2;ctx.setLineDash([9,7]);ctx.beginPath();ctx.moveTo(e.x,e.y);ctx.lineTo(e.x+Math.cos(e.chargeAngle)*190,e.y+Math.sin(e.chargeAngle)*190);ctx.stroke();ctx.restore();}if(e.signatureTell>0){ctx.strokeStyle=e.color;ctx.globalAlpha=.65;ctx.lineWidth=2;ctx.beginPath();ctx.arc(e.x,e.y,e.r+22+Math.sin(time*8)*3,0,TAU);ctx.stroke();}}
 drawEffects();
 for(const ex of nr15State.explosions){let t=(time-ex.born)/ex.duration;if(t<0||t>1)continue;let r=ex.size*(.2+Math.sqrt(t)*1.5);ctx.save();ctx.globalCompositeOperation='lighter';ctx.globalAlpha=Math.pow(1-t,2)*.75;let g=ctx.createRadialGradient(ex.x,ex.y,0,ex.x,ex.y,r);g.addColorStop(0,'#fff6c9');g.addColorStop(.12,'#ffd38c');g.addColorStop(.38,ex.color);g.addColorStop(1,ex.color+'00');ctx.fillStyle=g;ctx.beginPath();ctx.arc(ex.x,ex.y,r,0,TAU);ctx.fill();ctx.globalAlpha=(1-t)*.65;ctx.strokeStyle=ex.color;ctx.lineWidth=1.5;ctx.beginPath();ctx.ellipse(ex.x,ex.y,r*1.3,r*.8,0,0,TAU);ctx.stroke();ctx.restore();}
 ctx.restore();ctx.globalAlpha=1;ctx.globalCompositeOperation='source-over';if(state==='playing'||state==='paused'){drawTargetIndicator();if(!coarse)drawMinimap();}}
let nr15PreviewId='';
function nr15Render(force=false){if(nr15State.mode==='webgl2'&&nr15State.engine&&!nr15State.engine.ready(force))return;const now=performance.now();const key=[state,W,H,selectedRig,nr15State.quality,G?.wave||0,save.motion].join('/');if(!force&&state!=='playing'&&state!=='home'&&state!=='transit'&&nr15State.staticKey===key)return;if(!force&&coarse&&nr15State.quality!=='ultra'&&key===nr15State.staticKey&&now-(nr15State.lastPaint||0)<32)return;nr15State.lastPaint=now;nr15State.staticKey=key;if(!nr15State.engine||nr15State.mode!=='webgl2'||nr15State.quality==='compatibility'){nr15OriginalRender();return;}const start=performance.now();try{const time=player&&G?G.elapsed:ambientTime;nr15State.explosions=nr15State.explosions.filter(e=>time-e.born<e.duration&&time>=e.born);nr15State.debris=nr15State.debris.filter(e=>time-e.born<e.life&&time>=e.born);if(nr15PreviewId!==selectedRig){nr15PreviewId=selectedRig;nr15Sync();}if(!player)nr15Measure();const view=nr15Prepare(time);nr15State.engine.render({width:W,height:H,...view,time:save.motion?0:time,zone:nr15Zone(),location:NR16World.destinations[nr15Zone()],accent:nr15Regions[nr15Zone()].accent,pulse:save.motion?0:player&&player.overdrive>0?.8:0,hurt:hurtFlash,mobile:coarse,impacts:save.motion?[]:nr15State.explosions.slice(-3).map(ex=>{let t=clamp((time-ex.born)/ex.duration,0,1);return[((ex.x-view.cx)*view.zoom+W/2)/W,1-((ex.y-view.cy)*view.zoom+H/2)/H,ex.size*(.2+Math.sqrt(t)*1.5)*view.zoom/H,(1-t)*.0035];})});nr15Overlay(time,view);nr15State.frames++;if(nr15State.frames%15===0)nr16GraphicsStatus();nr15State.renderMs=performance.now()-start;}catch(e){nr15Fallback('Render error: '+e.message);nr15OriginalRender();}}
const nr15OriginalKill=killEnemy;
killEnemy=function(e){let dead=e?.dead;nr15OriginalKill(e);if(!e||dead||!e.dead)return;let boss=e.type==='boss',time=G?.elapsed||0;nr15State.explosions.push({x:e.x,y:e.y,born:time,duration:boss?1.4:.58,size:boss?110:e.r*1.6,color:boss?'#ffb35f':'#ec844e'});if(nr15State.explosions.length>16)nr15State.explosions.shift();let count=coarse?(boss?8:2):(boss?13:4);for(let i=0;i<count;i++){let a=e.id*1.37+i*2.39;nr15State.debris.push({x:e.x,y:e.y,born:time,life:boss?1.5:.8,vx:Math.cos(a)*(boss?190:85),vy:Math.sin(a)*(boss?190:85),a,spin:(i%2?1:-1)*4,s:boss?.20:.09,model:i%2?'gunner':'striker'});}if(nr15State.debris.length>65)nr15State.debris.splice(0,nr15State.debris.length-65);};
const nr15OriginalNext=nextSector;
nextSector=function(){
 if(player){player.x=WORLD.w/2;player.y=WORLD.h/2;player.vx=0;player.vy=0;player.dashTime=0;player.angle=-Math.PI/2;camera.x=player.x;camera.y=player.y;}
 particles=[];rings=[];arcs=[];trails=[];floaters=[];nr15State.explosions=[];nr15State.debris=[];shake=0;hurtFlash=0;
 document.body.classList.remove('nr-boss-intro');clearTimeout(nr15State.bossIntro);
 nr15OriginalNext();nr15State.staticKey='';nr15Sync();
 if(G?.wave%3===0){$('nrBossTitle').textContent=typeof bossDisplayName==='function'?bossDisplayName(Math.min(3,G.wave/3)):'CAPITAL CONTACT';$('nrBossClass').textContent=['ARMORED SIEGE CARRIER','TRI-CORE ASSAULT PLATFORM','SOVEREIGN COMMAND VESSEL'][Math.min(2,G.wave/3-1)];document.body.classList.add('nr-boss-intro');nr15State.bossIntro=setTimeout(()=>document.body.classList.remove('nr-boss-intro'),save.motion?600:1450);}
};
const nr15OriginalStart=startRun;
startRun=function(...args){nr15State.explosions=[];nr15State.debris=[];document.body.classList.remove('nr-boss-intro');return nr15OriginalStart(...args);};
const nr15OriginalHUD=refreshHUD;
refreshHUD=function(){nr15OriginalHUD();nr15Sync();if($('nrAreaLabel'))$('nrAreaLabel').textContent=nr15Regions[nr15Zone()].name;};
const nr15OriginalHome=returnHome;
returnHome=function(){nr15State.explosions=[];nr15State.debris=[];document.body.classList.remove('nr-boss-intro');nr15OriginalHome();nr15Measure();};
render=nr15Render;
window.NEON_RIFT_VERSION='1.6.0';
window.__NEON_RIFT_VISUAL__=Object.freeze({version:'1.6.0',get renderer(){return nr15State.mode;},get reason(){return nr15State.reason;},get profile(){return nr15State.quality;}});
queueMicrotask(()=>{nr15Init();nr15BuildUI();});
if(new URLSearchParams(location.search).has('test')){window.__NR15_QA={get status(){return {mode:nr15State.mode,reason:nr15State.reason,quality:nr15State.quality,zone:nr15State.zone,drawCalls:nr15State.engine?.drawCalls,triangles:nr15State.engine?.triangles,size:nr15State.engine?[nr15State.engine.w,nr15State.engine.h]:null,models:nr15State.engine?.models.size,frames:nr15State.frames,renderMs:nr15State.renderMs};},render:()=>nr15Render(true),loseContext(){nr15State.engine?.gl.getExtension('WEBGL_lose_context')?.loseContext();},error(){return nr15State.engine?.gl.getError();},killBoss(){if(G?.boss)killEnemy(G.boss);},get rng(){return G?.rngCalls;},setQuality(q){nr15State.quality=q;nr15ApplyQuality();},rawModel:id=>NR15Art.ship(id).vertices.length/10};}
